# Site Settings
locale                   : "en-US"
title                    : "Yilin Jia's Homepage"
title_separator          : "-"
name                     : "Yilin Jia"
description              : "Personal website of Yilin Jia"
url                      : https://tic-top.github.io
baseurl                  : ""
repository               : "tic-top/tic-top.github.io"
future                   : true

# Site Author
author:
  name             : "Yilin Jia"
  avatar           : "1.jpg"
  bio              : "Master at UMich CS. I love building things with AI."
  location         : "Michigan, USA"
  googlescholar    : "https://scholar.google.com/citations?user=mJODFtcAAAAJ&hl=en&oi=ao"
  email            : "kirp@umich.edu"
  github           : "tic-top"

# Reading Files
include:
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Gemfile
  - LICENSE
  - README
  - node_modules
  - package.json
  - vendor
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  publications:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: v2_post

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
